Citizen.CreateThread(function()
        AddTextEntry('0x7053099C', 'Mitsubishi EVO PJR')
        AddTextEntry('pjr', 'EVO')
        AddTextEntry('0xF35D60FA', 'Mitsubishi EVO PATROL')
        AddTextEntry('patrol', 'EVO')
        AddTextEntry('0x3C46CA3D', 'RAPTOR PJR')
        AddTextEntry('prraptor', 'RAPTOR')
        AddTextEntry('0x88453609', 'RIOT')
        AddTextEntry('riotid', 'RIOT ID')
        AddTextEntry('0xA26EE0EE', 'POLMAV')
        AddTextEntry('polmavid', 'POLMAV ID')
    end)